module View exposing (view)

import Html exposing (Html, node, text)
import Html.Attributes exposing (attribute, content, name, rel, type_)


view : Html m
view =
    node "!DOCTYPE"
        [ attribute "html" "" ]
        [ node "html"
            [ class "no-js", lang "en" ]
            [ node "head"
                []
                [ node "meta"
                    [ charset "UTF-8" ]
                    []
                , node "meta"
                    [ content "IE=edge,chrome=1", attribute "http-equiv" "X-UA-Compatible" ]
                    []
                , node "meta"
                    [ content "width=device-width, initial-scale=1.0", name "viewport" ]
                    []
                , node "title"
                    []
                    [ text "A Collection of Page Transitions" ]
                , node "meta"
                    [ content "A Collection of Page Transitions with CSS Animations", name "description" ]
                    []
                , text "    "
                , node "meta"
                    [ content "page transition, css animation, website, effect, css3, jquery", name "keywords" ]
                    []
                , text "    "
                , node "meta"
                    [ content "Codrops", name "author" ]
                    []
                , node "link"
                    [ href "../favicon.ico", rel "shortcut icon" ]
                    []
                , node "link"
                    [ href "css/default.css", rel "stylesheet", type_ "text/css" ]
                    []
                , text "    "
                , node "link"
                    [ href "css/multilevelmenu.css", rel "stylesheet", type_ "text/css" ]
                    []
                , text "    "
                , node "link"
                    [ href "css/component.css", rel "stylesheet", type_ "text/css" ]
                    []
                , text "    "
                , node "link"
                    [ href "css/animations.css", rel "stylesheet", type_ "text/css" ]
                    []
                , node "script"
                    [ src "js/modernizr.custom.js" ]
                    []
                ]
            , body []
                [ div [ class "codrops-top clearfix" ]
                    [ a [ class "codrops-icon codrops-icon-prev", href "http://tympanus.net/Tutorials/AutomaticFigureNumbering/" ]
                        [ span []
                            [ text "Previous Demo" ]
                        ]
                    , span [ class "right" ]
                        [ a [ class "codrops-icon codrops-icon-drop", href "http://tympanus.net/codrops/?p=15001" ]
                            [ span []
                                [ text "Back to the Codrops Article" ]
                            ]
                        ]
                    ]
                , div [ class "pt-triggers" ]
                    [ button [ class "pt-touch-button", id "iterateEffects" ]
                        [ text "Show next page transition" ]
                    , div [ class "dl-menuwrapper", id "dl-menu" ]
                        [ button [ class "dl-trigger" ]
                            [ text "Choose a transition" ]
                        , ul [ class "dl-menu" ]
                            [ li []
                                [ a [ href "#" ]
                                    [ text "Move" ]
                                , ul [ class "dl-submenu" ]
                                    [ li [ attribute "data-animation" "1" ]
                                        [ a [ href "#" ]
                                            [ text "Move to left/ from right" ]
                                        ]
                                    , li [ attribute "data-animation" "2" ]
                                        [ a [ href "#" ]
                                            [ text "Move to right/ from left" ]
                                        ]
                                    , li [ attribute "data-animation" "3" ]
                                        [ a [ href "#" ]
                                            [ text "Move to top/ from bottom" ]
                                        ]
                                    , li [ attribute "data-animation" "4" ]
                                        [ a [ href "#" ]
                                            [ text "Move to bottom/ from top" ]
                                        ]
                                    ]
                                ]
                            , li []
                                [ a [ href "#" ]
                                    [ text "Fade" ]
                                , ul [ class "dl-submenu" ]
                                    [ li [ attribute "data-animation" "5" ]
                                        [ a [ href "#" ]
                                            [ text "Fade / from right" ]
                                        ]
                                    , li [ attribute "data-animation" "6" ]
                                        [ a [ href "#" ]
                                            [ text "Fade / from left" ]
                                        ]
                                    , li [ attribute "data-animation" "7" ]
                                        [ a [ href "#" ]
                                            [ text "Fade / from bottom" ]
                                        ]
                                    , li [ attribute "data-animation" "8" ]
                                        [ a [ href "#" ]
                                            [ text "Fade / from top" ]
                                        ]
                                    , li [ attribute "data-animation" "9" ]
                                        [ a [ href "#" ]
                                            [ text "Fade left / Fade right" ]
                                        ]
                                    , li [ attribute "data-animation" "10" ]
                                        [ a [ href "#" ]
                                            [ text "Fade right / Fade left" ]
                                        ]
                                    , li [ attribute "data-animation" "11" ]
                                        [ a [ href "#" ]
                                            [ text "Fade top / Fade bottom" ]
                                        ]
                                    , li [ attribute "data-animation" "12" ]
                                        [ a [ href "#" ]
                                            [ text "Fade bottom / Fade top" ]
                                        ]
                                    ]
                                ]
                            , li []
                                [ a [ href "#" ]
                                    [ text "Different easing" ]
                                , ul [ class "dl-submenu" ]
                                    [ li [ attribute "data-animation" "13" ]
                                        [ a [ href "#" ]
                                            [ text "Different easing / from right" ]
                                        ]
                                    , li [ attribute "data-animation" "14" ]
                                        [ a [ href "#" ]
                                            [ text "Different easing / from left" ]
                                        ]
                                    , li [ attribute "data-animation" "15" ]
                                        [ a [ href "#" ]
                                            [ text "Different easing / from bottom" ]
                                        ]
                                    , li [ attribute "data-animation" "16" ]
                                        [ a [ href "#" ]
                                            [ text "Different easing / from top" ]
                                        ]
                                    ]
                                ]
                            , li []
                                [ a [ href "#" ]
                                    [ text "Scale" ]
                                , ul [ class "dl-submenu" ]
                                    [ li [ attribute "data-animation" "17" ]
                                        [ a [ href "#" ]
                                            [ text "Scale down / from right" ]
                                        ]
                                    , li [ attribute "data-animation" "18" ]
                                        [ a [ href "#" ]
                                            [ text "Scale down / from left" ]
                                        ]
                                    , li [ attribute "data-animation" "19" ]
                                        [ a [ href "#" ]
                                            [ text "Scale down / from bottom" ]
                                        ]
                                    , li [ attribute "data-animation" "20" ]
                                        [ a [ href "#" ]
                                            [ text "Scale down / from top" ]
                                        ]
                                    , li [ attribute "data-animation" "21" ]
                                        [ a [ href "#" ]
                                            [ text "Scale down / scale down" ]
                                        ]
                                    , li [ attribute "data-animation" "22" ]
                                        [ a [ href "#" ]
                                            [ text "Scale up / scale up" ]
                                        ]
                                    , li [ attribute "data-animation" "23" ]
                                        [ a [ href "#" ]
                                            [ text "Move to left / scale up" ]
                                        ]
                                    , li [ attribute "data-animation" "24" ]
                                        [ a [ href "#" ]
                                            [ text "Move to right / scale up" ]
                                        ]
                                    , li [ attribute "data-animation" "25" ]
                                        [ a [ href "#" ]
                                            [ text "Move to top / scale up" ]
                                        ]
                                    , li [ attribute "data-animation" "26" ]
                                        [ a [ href "#" ]
                                            [ text "Move to bottom / scale up" ]
                                        ]
                                    , li [ attribute "data-animation" "27" ]
                                        [ a [ href "#" ]
                                            [ text "Scale down / scale up" ]
                                        ]
                                    ]
                                ]
                            , li []
                                [ a [ href "#" ]
                                    [ text "Rotate" ]
                                , ul [ class "dl-submenu" ]
                                    [ li []
                                        [ a [ href "#" ]
                                            [ text "Glue" ]
                                        , ul [ class "dl-submenu" ]
                                            [ li [ attribute "data-animation" "28" ]
                                                [ a [ href "#" ]
                                                    [ text "Glue left / from right" ]
                                                ]
                                            , li [ attribute "data-animation" "29" ]
                                                [ a [ href "#" ]
                                                    [ text "Glue right / from left" ]
                                                ]
                                            , li [ attribute "data-animation" "30" ]
                                                [ a [ href "#" ]
                                                    [ text "Glue bottom / from top" ]
                                                ]
                                            , li [ attribute "data-animation" "31" ]
                                                [ a [ href "#" ]
                                                    [ text "Glue top / from bottom" ]
                                                ]
                                            ]
                                        ]
                                    , li []
                                        [ a [ href "#" ]
                                            [ text "Flip" ]
                                        , ul [ class "dl-submenu" ]
                                            [ li [ attribute "data-animation" "32" ]
                                                [ a [ href "#" ]
                                                    [ text "Flip right" ]
                                                ]
                                            , li [ attribute "data-animation" "33" ]
                                                [ a [ href "#" ]
                                                    [ text "Flip left" ]
                                                ]
                                            , li [ attribute "data-animation" "34" ]
                                                [ a [ href "#" ]
                                                    [ text "Flip top" ]
                                                ]
                                            , li [ attribute "data-animation" "35" ]
                                                [ a [ href "#" ]
                                                    [ text "Flip bottom" ]
                                                ]
                                            ]
                                        ]
                                    , li [ attribute "data-animation" "36" ]
                                        [ a [ href "#" ]
                                            [ text "Fall" ]
                                        ]
                                    , li [ attribute "data-animation" "37" ]
                                        [ a [ href "#" ]
                                            [ text "Newspaper" ]
                                        ]
                                    , li []
                                        [ a [ href "#" ]
                                            [ text "Push / Pull" ]
                                        , ul [ class "dl-submenu" ]
                                            [ li [ attribute "data-animation" "38" ]
                                                [ a [ href "#" ]
                                                    [ text "Push left / from right" ]
                                                ]
                                            , li [ attribute "data-animation" "39" ]
                                                [ a [ href "#" ]
                                                    [ text "Push right / from left" ]
                                                ]
                                            , li [ attribute "data-animation" "40" ]
                                                [ a [ href "#" ]
                                                    [ text "Push top / from bottom" ]
                                                ]
                                            , li [ attribute "data-animation" "41" ]
                                                [ a [ href "#" ]
                                                    [ text "Push bottom / from top" ]
                                                ]
                                            , li [ attribute "data-animation" "42" ]
                                                [ a [ href "#" ]
                                                    [ text "Push left / pull right" ]
                                                ]
                                            , li [ attribute "data-animation" "43" ]
                                                [ a [ href "#" ]
                                                    [ text "Push right / pull left" ]
                                                ]
                                            , li [ attribute "data-animation" "44" ]
                                                [ a [ href "#" ]
                                                    [ text "Push top / pull bottom" ]
                                                ]
                                            , li [ attribute "data-animation" "45" ]
                                                [ a [ href "#" ]
                                                    [ text "Push bottom / pull top" ]
                                                ]
                                            ]
                                        ]
                                    , li []
                                        [ a [ href "#" ]
                                            [ text "Fold / Unfold" ]
                                        , ul [ class "dl-submenu" ]
                                            [ li [ attribute "data-animation" "46" ]
                                                [ a [ href "#" ]
                                                    [ text "Fold left / from right" ]
                                                ]
                                            , li [ attribute "data-animation" "47" ]
                                                [ a [ href "#" ]
                                                    [ text "Fold right / from left" ]
                                                ]
                                            , li [ attribute "data-animation" "48" ]
                                                [ a [ href "#" ]
                                                    [ text "Fold top / from bottom" ]
                                                ]
                                            , li [ attribute "data-animation" "49" ]
                                                [ a [ href "#" ]
                                                    [ text "Fold bottom / from top" ]
                                                ]
                                            , li [ attribute "data-animation" "50" ]
                                                [ a [ href "#" ]
                                                    [ text "Move to right / unfold left" ]
                                                ]
                                            , li [ attribute "data-animation" "51" ]
                                                [ a [ href "#" ]
                                                    [ text "Move to left / unfold right" ]
                                                ]
                                            , li [ attribute "data-animation" "52" ]
                                                [ a [ href "#" ]
                                                    [ text "Move to bottom / unfold top" ]
                                                ]
                                            , li [ attribute "data-animation" "53" ]
                                                [ a [ href "#" ]
                                                    [ text "Move to top / unfold bottom" ]
                                                ]
                                            ]
                                        ]
                                    , li []
                                        [ a [ href "#" ]
                                            [ text "Room" ]
                                        , ul [ class "dl-submenu" ]
                                            [ li [ attribute "data-animation" "54" ]
                                                [ a [ href "#" ]
                                                    [ text "Room to left" ]
                                                ]
                                            , li [ attribute "data-animation" "55" ]
                                                [ a [ href "#" ]
                                                    [ text "Room to right" ]
                                                ]
                                            , li [ attribute "data-animation" "56" ]
                                                [ a [ href "#" ]
                                                    [ text "Room to top" ]
                                                ]
                                            , li [ attribute "data-animation" "57" ]
                                                [ a [ href "#" ]
                                                    [ text "Room to bottom" ]
                                                ]
                                            ]
                                        ]
                                    , li []
                                        [ a [ href "#" ]
                                            [ text "Cube" ]
                                        , ul [ class "dl-submenu" ]
                                            [ li [ attribute "data-animation" "58" ]
                                                [ a [ href "#" ]
                                                    [ text "Cube to left" ]
                                                ]
                                            , li [ attribute "data-animation" "59" ]
                                                [ a [ href "#" ]
                                                    [ text "Cube to right" ]
                                                ]
                                            , li [ attribute "data-animation" "60" ]
                                                [ a [ href "#" ]
                                                    [ text "Cube to top" ]
                                                ]
                                            , li [ attribute "data-animation" "61" ]
                                                [ a [ href "#" ]
                                                    [ text "Cube to bottom" ]
                                                ]
                                            ]
                                        ]
                                    , li []
                                        [ a [ href "#" ]
                                            [ text "Carousel" ]
                                        , ul [ class "dl-submenu" ]
                                            [ li [ attribute "data-animation" "62" ]
                                                [ a [ href "#" ]
                                                    [ text "Carousel to left" ]
                                                ]
                                            , li [ attribute "data-animation" "63" ]
                                                [ a [ href "#" ]
                                                    [ text "Carousel to right" ]
                                                ]
                                            , li [ attribute "data-animation" "64" ]
                                                [ a [ href "#" ]
                                                    [ text "Carousel to top" ]
                                                ]
                                            , li [ attribute "data-animation" "65" ]
                                                [ a [ href "#" ]
                                                    [ text "Carousel to bottom" ]
                                                ]
                                            ]
                                        ]
                                    , li [ attribute "data-animation" "66" ]
                                        [ a [ href "#" ]
                                            [ text "Sides" ]
                                        ]
                                    ]
                                ]
                            , li [ attribute "data-animation" "67" ]
                                [ a [ href "#" ]
                                    [ text "Slide" ]
                                ]
                            ]
                        ]
                    , text "    "
                    ]
                , div [ class "pt-perspective", id "pt-main" ]
                    [ div [ class "pt-page pt-page-1" ]
                        [ h1 []
                            [ span []
                                [ text "A collection of" ]
                            , strong []
                                [ text "Page" ]
                            , text "Transitions"
                            ]
                        ]
                    , div [ class "pt-page pt-page-2" ]
                        [ h1 []
                            [ span []
                                [ text "A collection of" ]
                            , strong []
                                [ text "Page" ]
                            , text "Transitions"
                            ]
                        ]
                    , div [ class "pt-page pt-page-3" ]
                        [ h1 []
                            [ span []
                                [ text "A collection of" ]
                            , strong []
                                [ text "Page" ]
                            , text "Transitions"
                            ]
                        ]
                    , div [ class "pt-page pt-page-4" ]
                        [ h1 []
                            [ span []
                                [ text "A collection of" ]
                            , strong []
                                [ text "Page" ]
                            , text "Transitions"
                            ]
                        ]
                    , div [ class "pt-page pt-page-5" ]
                        [ h1 []
                            [ span []
                                [ text "A collection of" ]
                            , strong []
                                [ text "Page" ]
                            , text "Transitions"
                            ]
                        ]
                    , div [ class "pt-page pt-page-6" ]
                        [ h1 []
                            [ span []
                                [ text "A collection of" ]
                            , strong []
                                [ text "Page" ]
                            , text "Transitions"
                            ]
                        ]
                    ]
                , div [ class "pt-message" ]
                    [ p []
                        [ text "Your browser does not support CSS animations." ]
                    ]
                , node "script"
                    [ src "https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" ]
                    []
                , node "script"
                    [ src "js/jquery.dlmenu.js" ]
                    []
                , node "script"
                    [ src "js/pagetransitions.js" ]
                    []
                ]
            ]
        ]
